#!/bin/bash
#TOOLS_SCRIPT_HOME="/home/zc/bryantchang/Linux-Scripts/System_scripts/ssh"
TOOLS_SCRIPT_HOME="/home/hadoop/bryantchang/tools/Scripts/System_scripts/ssh"
SAMPLE_COUNT=75
MEM_STEP=200
MEM_PER_PAR=3
SLAVE_HOST=spark2
EVENTMAP_CONF="eventmap.properties"
METRICS_CLASSIFY_CONF="metric_classify"
METRICS_REGRESSION_CONF="metric_regression"
MONITOR_INTERNAL=1
CATE_NO=4
