#!/bin/bash
#TOOLS_SCRIPT_HOME="/home/zc/bryantchang/Linux-Scripts/System_scripts/ssh"
TOOLS_SCRIPT_HOME="/home/hadoop/bryantchang/tools/Scripts/System_scripts/ssh"
SAMPLE_COUNT=75
MEM_STEP=200
MEM_PER_PAR=3
SLAVE_HOST=spark2
EVENTMAP_CONF="eventmap.properties"
MONITOR_INTERNAL=1
